### ISSUE TITLE
gl.ShaderSource() throws "unexpected fault address" in Windows 64

### ISSUE THREAD

**Issue by metaleap** [chsc/gogl#7] opened 2012-05-01 23:10 UTC
Or am I doing it wrong? The following helper function of mine works fine with gl42 under Linux:

```
func glSetShaderSource (shader gl.Uint, source string) {
    var src = gl.GLStringArray(source)
    defer gl.GLStringArrayFree(src)
    gl.ShaderSource(shader, gl.Sizei(len(src)), &src[0], nil)
}
```

From previous threads here I understand that this is essentially the clean way to pass a Go string to the GLSL shader compiler, and indeed under Linux it works well.

Under Windows 64-bit, Go 1.0.1 64-bit, the last line (not the deferred GLStringArrayFree but the gl.ShaderSource call) crashes the program with the following console output:

```
unexpected fault address 0x100000001
throw: fault
[signal 0xc0000005 code=0x8 addr=0x100000001 pc=0x100000001]

goroutine 1 [syscall]:

goroutine 2 [syscall]:
created by runtime.main
        C:/Users/ADMINI~1/AppData/Local/Temp/2/bindist269497170/go/src/pkg/runtime/proc.c:221
```

Happens for both gogl42 and gogl33.

**Comment by chsc** [comment] 2012-06-01 08:56
For me, it's hard to reproduce the problem, because I haven't a 64 bit Windows install on my computer. It seems to be a cgo problem with 64bit Windows. Maybe the size of the arguments passed to the native function? I don't know.
Sorry, it' still remains an open issue :(

**Comment by metaleap** [comment] 2012-06-01 09:55
Yeah no prob... went back to Linux for now  :D

**Comment by ghost** [comment] 2012-09-05 16:59
You should try it again with recent Go versions. gl.ShaderSource() works for me :)

Closed Windows 64 bug:
http://code.google.com/p/go/issues/detail?id=3662)

**Comment by chsc** [comment] 2012-09-06 18:14
Great, it seems that I can close this issue now ;)

**Closed as completed by chsc** 2012-09-06 18:14 UTC
